### ISSUE TITLE
app's location permission page automatically opens on app launch when "ACCESS_BACKGROUND_LOCATION" is defined in the androidManifest file

### ISSUE THREAD

**Issue by NeatFastro** [DwayneCoussement/flutter_geofence#54] opened 2022-03-23 11:32 UTC
When the app get's launched then the package automatically asks for location permissions and on android 11 this results in opening the app's location permissions page instead of showing a dialog.

flutter: 2.10.2
flutter_geofence: 0.4.2

**Comment by NeatFastro** [comment] 2022-03-28 20:01
Is anyone here?

**Comment by mvarendorff** [comment] 2022-04-19 09:52
Duplicate of #41 ?

**Comment by NeatFastro** [comment] 2022-04-21 10:20
looks like @mvarendorff already made a PR for this issue, and it just removes the invocation of "requestPermission" method in two places, can you (@geisterfurz007)  please review and merge it?

**Comment by mvarendorff** [comment] 2022-04-21 10:48
I am not a maintainer on this repo so no can do, sorry!

**Comment by mvarendorff** [comment] 2022-04-25 08:58
The PR has been closed, it seems but there hasn't been a new release yet. If you need the fix immediately, you can set the dependency like this:

```yml
  flutter_geofence:
    git:
      url: https://github.com/DwayneCoussement/flutter_geofence
      ref: main
```

**Comment by NeatFastro** [comment] 2022-04-28 11:22
Thanks for the tip

**Closed as completed** 2022-05-17 09:37 UTC
